TrangTuyenDung/Areas/Staff/Controllers/ConfirmInternController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TrangTuyenDung.Models;
using ClosedXML.Excel;
using System.Data;
using System.IO;
using Newtonsoft.Json;
using Microsoft.Ajax.Utilities;
using Newtonsoft.Json.Linq;

namespace TrangTuyenDung.Areas.Staff.Controllers {
    [Authorize(Roles = "Staff")]


    public class ConfirmInternController : Controller {
        EJobEntities db = new EJobEntities();

        public ActionResult List(string message =null) {
            if(message == "Fail") {
                ViewBag.Message = "Fail";
            }
            var model = db.confirmation_intern.OrderByDescending(x => x.id).ToList();
            return View(model);
        }

        public ActionResult Preview(int id) {
            var data = db.confirmation_intern.FirstOrDefault(x => x.id == id);
            var student_district = db.Districts.FirstOrDefault(x => x.Id == data.student_district_id);
            var student_province = db.Provinces.FirstOrDefault(x => x.Id == data.student_province_id);
            var org_district = db.Districts.FirstOrDefault(x => x.Id == data.student_district_id);
            var org_province = db.Provinces.FirstOrDefault(x => x.Id == data.student_province_id);
            var major = db.Faculties_Majors.FirstOrDefault(x => x.Id == data.major_id);
            var faculty = db.Faculties.FirstOrDefault(x => x.Id == data.faculty_id);
            ViewBag.student_dictrict = student_district.Type + " " + student_district.District_Name;
            ViewBag.org_dictrict = org_district.Type + " " + org_district.District_Name;
            ViewBag.student_provinces = student_province.Type + " " + student_province.Name;
            ViewBag.org_provinces = org_province.Type + " " + org_province.Name;
            ViewBag.major = major.Name;
            ViewBag.faculty = faculty.Name;
            return View(data);
        }

        [HttpPost]
        public ActionResult Export(string startDay, string endDay) {
            var start = DateTime.Parse(startDay);
            var end = DateTime.Parse(endDay);
            var model = db.confirmation_intern.Where(x => x.create_day >= start && x.create_day <= end).OrderByDescending(x => x.id).ToList();

          if(model != null) {
                DataTable dt = new DataTable("Grid");
                dt.Columns.AddRange(new DataColumn[33] {new DataColumn("Ngày tạo"),
                                            new DataColumn("Tên sinh viên"),
                                            new DataColumn("MSSV"),
                                            new DataColumn("Lớp"),
                                            new DataColumn("Bậc đào tạo"),
                                            new DataColumn("Khoa"),
                                            new DataColumn("Ngành học"),
                                            new DataColumn("Năm học"),
                                            new DataColumn("Số điện thoại"),
                                            new DataColumn("Email"),
                                            new DataColumn("Địa chỉ sinh viên"),
                                            new DataColumn("Hình thức thực tập"),
                                            new DataColumn("Học kỳ thực tập"),
                                            new DataColumn("Vị trí thực tập"),
                                            new DataColumn("Phòng ban"),
                                            new DataColumn("Thực tập từ"),
                                            new DataColumn("Thực tập đến"),
                                            new DataColumn("Lịch thực tập"),
                                            new DataColumn("Tên Công ty"),
                                            new DataColumn("Website"),
                                            new DataColumn("Tax"),
                                            new DataColumn("Số điện thoại doanh nghiệp"),
                                            new DataColumn("Địa chỉ doanh nghiệp"),
                                            new DataColumn("Tên nhân sự tiếp nhân thực tập"),
                                            new DataColumn("Chức vụ của nhân sự tiếp nhận thực tập"),
                                            new DataColumn("Số điện thoại bàn của nhân sự tiếp nhận thực tập"),
                                            new DataColumn("Email của nhân sự tiếp nhận thực tập"),
                                            new DataColumn("Số di động của nhân sự tiếp nhận thực tập"),
                                            new DataColumn("Tên nhân sự hướng dẫn thực tập"),
                                            new DataColumn("Chức vụ của nhân sự hướng dẫn thực tập"),
                                            new DataColumn("Số điện thoại bàn của nhân sự hướng dẫn thực tập"),
                                            new DataColumn("Email của nhân sự hướng dẫn thực tập"),
                                            new DataColumn("Số điện thoại di động của nhân sự hướng dẫn")});

                foreach (var intern in model) {
                    var level = "Cao đẳng";
                    var semester = "";
                    //student address
                    var stu_dict = db.Districts.FirstOrDefault(x => x.Id == intern.student_district_id);
                    var stu_pro = db.Provinces.FirstOrDefault(x => x.Id == intern.student_province_id);
                    var student_add = intern.student_street+"," + "Phường " + intern.student_ward+","+ stu_dict.Type+" "+ stu_dict.District_Name +","+ stu_pro.Type+" "+stu_pro.Name;
  
                
                    JArray arr = JArray.Parse(intern.schedule_work);

                    var result = "";
                    var jsonResponse = JToken.Parse("[]");
                    foreach (var schedule in arr) {
                        var day = schedule["day"];
                        if (day.HasValues == true) {
                            var workingTime = "Thời gian làm việc: ";
                            
                            var startTime = schedule["start"];
                            var endTime = schedule["end"];

                            foreach (var item in day) {
                                workingTime += "Thứ " + item + ",";
                            }

                            workingTime = workingTime.Substring(0, workingTime.Length - 1);
                            result += workingTime +" bắt đầu vào lúc : "+startTime + " và kết thúc vào lúc : "+endTime+ ",";
                        }
                    }
                    var schedule_word = "";
                    if (result != "") {
                        schedule_word = result.Substring(0, result.Length - 1);
                    }
                   

                   
                    // org address
                    var org_dict = db.Districts.FirstOrDefault(x => x.Id == intern.org_district_id);
                    var org_pro = db.Provinces.FirstOrDefault(x => x.Id == intern.org_province_id);
                    var org_add = intern.org_street +","+"Phường " +intern.org_ward +","+org_dict.Type+" "+org_dict.District_Name +","+org_pro.Type+" "+ org_pro.Name;
                    var faculty = db.Faculties.FirstOrDefault(x => x.Id == intern.faculty_id);
                    var interntype = intern.other_type_intern;
                    var major = db.Faculties_Majors.FirstOrDefault(x => x.Id == intern.major_id);
                    // check level
                    if (intern.level_id == 0) {
                        level = "Đại học";
                    }
                    //check semester intern
                    if (intern.semester == 0) {
                        semester = "HK 1";
                    }
                    else if (intern.semester == 1) {
                        semester = "HK 2";
                    }
                    else {
                        semester = "HK hè";
                    }
                    //check intern type
                    if (intern.type_intern == 0) {
                        interntype = "Thực tập tốt nghiệp";
                    }
                    else if (intern.type_intern == 1) {
                        interntype = "Thực tập nghề nghiệp";
                    }

                    dt.Rows.Add(intern.create_day,intern.student_name, intern.student_id, intern.student_class, level, faculty.Name, major.Name, intern.school_year, intern.cellphone, intern.student_email, student_add, interntype, semester, intern.position, intern.department, intern.start_day, intern.end_day, schedule_word, intern.organization_name, intern.website, intern.tax, intern.org_telephone, org_add, intern.human_resource_name, intern.human_resource_position, intern.human_resource_position_tel, intern.human_resource_email, intern.human_resource_cel, intern.supervisor_name, intern.supervisor_position, intern.supervisor_tel, intern.supervisor_email, intern.supervisor_cellphone);

                }

                using (XLWorkbook wb = new XLWorkbook()) {
                    wb.Worksheets.Add(dt);
                    using (MemoryStream stream = new MemoryStream()) {
                        wb.SaveAs(stream);
                        return File(stream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "PTNTT.xlsx");
                    }
                }
            }
            return HttpNotFound();
          
           
        }
    }
}

TrangTuyenDung/Areas/Student/Views/ConfirmIntern/Upload.cshtml
@model IEnumerable<TrangTuyenDung.Models.confirmation_intern>

    @{
        ViewBag.Title = "Upload Phiếu tiếp nhận thực";
        Layout = "~/Views/Shared/_Layout.cshtml";
        var countId = 0;
    }
    @section Styles {
        <!-- datatable boostrap4 -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.19/css/dataTables.bootstrap4.min.css" integrity="sha256-F+DaKAClQut87heMIC6oThARMuWne8+WzxIDT7jXuPA=" crossorigin="anonymous" />
    }

    <div class="container py-3">
        @if (ViewBag.Message == "success") {
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                <div>Phiếu tiếp nhận thực tập đã được Upload thành công</div>

                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        }

        @if (Model.Count() <= 0) {
            <div>Bạn chưa tạo phiếu tiếp nhận.</div>
        }
        else {
            <div class="table-responsive">
                <table class="table table-bordered" id="table" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Công ty thực tập</th>
                            <th>Ảnh xác nhận</th>
                            <th>Thao tác</th>
                        </tr>
                    </thead>
                    @if (Model.Count() > 10) {
                        <tfoot>
                            <tr>
                                <th>Công ty thực tập</th>
                                <th>Ảnh xác nhận</th>
                                <th>Thao tác</th>
                            </tr>
                        </tfoot>
                    }
                    <tbody>
                        @foreach (var item in Model) {
                            countId += 1;
                            <tr>
                                <td>
                                    @item.organization_name
                                </td>
                                <td>@item.link</td>
                                <td>
                                    @if (item.link == ""||item.link ==null) {
                                    using (Html.BeginForm("Upload", "ConfirmIntern", new { id = item.id }, FormMethod.Post, new { enctype = "multipart/form-data" })) {
                                        <label for="file" class="font-weight-medium">Upload phiếu tiếp nhận thực tập:</label>
                                        <!-- input file -->
                                        <div class="input-group">
                                            <div class="custom-file">
                                                <input type="file" name="file" id="file@(countId)" class="custom-file-input" accept="application/pdf">
                                                <label id="fileName@(countId)" class="custom-file-label text-muted" for="inputGroupFile04"></label>
                                            </div>
                                            <div class="input-group-append">
                                                <input class="btn btn-outline-primary" type="submit" value="Upload" />
                                            </div>
                                        </div>

                                        <!-- Error -->
                                        <div class="text-danger">
                                            <ul>
                                                <li>Kiểm tra thông tin trước khi upload, hệ thống chỉ nhận file pdf</li>
                                                <li>Format tên file: <span class="font-weight-medium text-danger">K#_MSSV_HọVàTênSV.pdf</span> (Khoá_MSSV_HọVàTênSV)</li>
                                            </ul>
                                        </div>
                                    }
                                    }
                                </td>
                            </tr>
                        
                       }
                    </tbody>
                </table>
            </div>
        }
    </div>

   @section scripts{
    <!-- dataTable -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.19/js/jquery.dataTables.min.js" integrity="sha256-t5ZQTZsbQi8NxszC10CseKjJ5QeMw5NINtOXQrESGSU=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.19/js/dataTables.bootstrap4.min.js" integrity="sha256-hJ44ymhBmRPJKIaKRf3DSX5uiFEZ9xB/qx8cNbJvIMU=" crossorigin="anonymous"></script>

    <!-- common func -->
    <script src="~/Scripts/common.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            initDatatable($('#table'));

            $(".custom-file-input").on("change", function (e) {
                const file = event.target.files[0]; // file
                const labelFileName = $(this).next(); // next element is Label input

                // Check capacity file
                if (file.size >= 5 * 1024 * 1024) {
                    alert("pdf tối đa 5MB, bạn vui lòng kiểm tra lại");
                    $(this).val(null);
                    labelFileName.text('');
                    return
                }

                if (!file.type.match('application/pdf')) {
                    alert("Chỉ nhận file PDF");
                    $(this).val(null);
                    labelFileName.text('');
                    return;
                }

                // Change lable to file named
                if (file && file.name) {
                    labelFileName.text(file.name);
                }
            });

            //uploadForm.on("submit", function () {
            //    const file = inputFile.val();

            //    if (file) {
            //        const fileType = file.split('.').pop();
            //        if (fileType === 'pdf') {
            //            return true;
            //        }
            //    }
            //    else {
            //        alert('Bạn chưa chọn file.');
            //        return false;
            //    }
            //});
        });
    </script>
}